apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-flask-app
  template:
    metadata:
      labels:
        app: gke-flask-app
    spec:
      containers:
      - name: flask01
        image: sabeerz/flask-app1:v1
        ports:
        - containerPort: 5000
          name: http-flask
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
spec:
  type: ClusterIP
  ports:
  - name: name-svc-port
    targetPort: http-flask
    port: 8080
    protocol: TCP
  selector:
    app: gke-flask-app
