apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  labels:
    app: flaskapp-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31080
    protocol: TCP
  selector:
    app: flaskapp
